<?php
/**
 * Editor shortcodes and TinyMCE controls.
 */

defined( 'ABSPATH' ) || exit;

/**
 * Render a CTA generated by the editor CTA modal.
 */
function payam_cta_shortcode( array $attributes, ?string $content = null ): string {
	$attributes = shortcode_atts(
		[
			'type' => 'primary',
			'icon' => 'yes',
			'url'  => '',
		],
		$attributes,
		'payam_cta'
	);

	$type = in_array( $attributes['type'], [ 'primary', 'secondary' ], true )
		? $attributes['type']
		: 'primary';
	$url  = esc_url( $attributes['url'] );
	$text = trim( wp_strip_all_tags( (string) $content ) );

	if ( '' === $url || '' === $text ) {
		return '';
	}

	$hasIcon = in_array( strtolower( (string) $attributes['icon'] ), [ '1', 'true', 'yes', 'on' ], true );
	$classes = 'cta-link cta-btn-' . $type . ( $hasIcon ? ' cta-has-icon text-body-3' : '' );
	$icon    = $hasIcon
		? icon( 'arrow-linear-2', 'w-5 h-5 fill-white' )
		: '';

	return sprintf(
		'<a href="%1$s" class="%2$s"><span>%3$s</span>%4$s</a>',
		$url,
		esc_attr( $classes ),
		esc_html( $text ),
		$icon
	);
}

add_shortcode( 'payam_cta', 'payam_cta_shortcode' );

/**
 * Preserve the theme's restricted SVG sprite markup when shortcode output is
 * passed through wp_kses_post(). No executable SVG elements are allowed.
 */
function payam_allow_shortcode_icon_markup( array $allowedTags, string $context ): array {
	if ( 'post' !== $context ) {
		return $allowedTags;
	}

	$allowedTags['svg'] = [
		'aria-hidden' => true,
		'class'       => true,
		'fill'        => true,
		'focusable'   => true,
		'height'      => true,
		'role'        => true,
		'viewbox'     => true,
		'width'       => true,
		'xmlns'       => true,
	];
	$allowedTags['use'] = [
		'href'       => true,
		'xlink:href' => true,
	];

	return $allowedTags;
}

add_filter( 'wp_kses_allowed_html', 'payam_allow_shortcode_icon_markup', 10, 2 );

/** Register the CTA generator for WordPress and ACF TinyMCE editors. */
function payam_register_cta_editor_button( array $plugins ): array {
	if ( ! current_user_can( 'edit_posts' ) && ! current_user_can( 'edit_pages' ) ) {
		return $plugins;
	}

	$scriptPath = '/assets/js/admin/cta-shortcode.min.js';

	$plugins['payam_cta'] = add_query_arg(
		'ver',
		payam_asset_version( $scriptPath ),
		get_theme_file_uri( $scriptPath )
	);

	return $plugins;
}

add_filter( 'mce_external_plugins', 'payam_register_cta_editor_button' );

/** Add the CTA generator button to the first TinyMCE toolbar. */
function payam_add_cta_editor_button( array $buttons ): array {
	if ( current_user_can( 'edit_posts' ) || current_user_can( 'edit_pages' ) ) {
		$buttons[] = 'payam_cta';
	}

	return $buttons;
}

add_filter( 'mce_buttons', 'payam_add_cta_editor_button' );

/** Ensure the button is also available in ACF WYSIWYG toolbar presets. */
function payam_add_cta_to_acf_toolbars( array $toolbars ): array {
	foreach ( $toolbars as &$toolbar ) {
		if ( ! isset( $toolbar[1] ) || ! is_array( $toolbar[1] ) ) {
			continue;
		}

		if ( ! in_array( 'payam_cta', $toolbar[1], true ) ) {
			$toolbar[1][] = 'payam_cta';
		}
	}
	unset( $toolbar );

	return $toolbars;
}

add_filter( 'acf/fields/wysiwyg/toolbars', 'payam_add_cta_to_acf_toolbars' );
